var squares = [
    "Very long thing here that is a lot of words and here is so much stuff",
    "blah1",
    "blah2",
    "blah3",
    "blah4",
    "blah5",
    "asdlfkjasdlkfjas;ldkfja;sdlkfja;sldkfja;lskdjf a;slkj as;ldk jfas;lf jasl;kfj asl;dkfj asdlk;fj asd;flkjas df;laksdjf ",
    "blah7",
    "blah8",
    "blah9",
    "😀😃😄💩💩💩💩💩💩💩",
    "blah11",
    "blah12",
    "blah13",
    "s",
    "blah15",
    "blah16",
    "blah17",
    "blah18",
    "blah19",
    "blah20",
    "blah21",
    "blah22",
    "blah23",
    "asldkfja;sldkgas;dlkfuwaoeiufjasl;dkghas;ldkf jasl;dkfj as;ldkfj as;ldkfja s;dlkfj asd;lkfja sd;lfkjasdf ;lksajd asd;lfkj s;dlkfja s;dlfkja sd;lkfj asl;fkjasd ;flkasjdf ;laskdjf a;sldkjf;lj lksdjflk ",
]

