var squares = [
    "&quot;Patriot&quot;",
    "American flag emoji",
    "&quot;Pure blood&quot;",
    "&quot;Jesus lover&quot;",
    "&quot;America First&quot;",
    "Some idiotic version of &quot;pronouns&quot;",
    "&quot;pronouns in bio lol&quot;",
    "&quot;I will not comply&quot;",
    "&quot;Stop the steal&quot;",
    "&quot;Lets go Brandon&quot; (or LGB)",
    "Crypto / NFTs",
    "MAGA",
    "ULTRA MAGA",
    "NUCLEAR ULTRA MAGA",
    "Q or Qanon",
    "WWG1WGA (Where We Go One, We Go All)",
    "Firstname Bunchanumbers",
    "Gab, Parler, Gettr, or Truth Social links",
    "&quot;Truth seeker&quot; / &quot;Truth Speaker&quot;",
    "Ivermectin",
    "&quot;Trump won&quot;",
    "&quot;Deep State&quot;",
    "&quot;Patriot Party&quot;",
    "#fjb (fuck joe biden)",
    "#KAG (Keep America Great)",
    "&quot;🚫 DMs&quot;",
    "&quot;🚫 RINOs&quot;",
    "&quot;Constitutional conservative&quot;",
    "&quot;Independent thinker&quot; / &quot;Critical thinker&quot;",
    "&quot;Fake news&quot;",
    "&quot;Blue Lives Matter&quot;",
    "&quot;The Big Lie&quot;",
    "#Audit2020",
    "&quot;shadow banned&quot;",
    "&quot;Drain the swamp&quot;",
    "&quot;Freedom loving&quot;",
    "NRA",
    "ΜΟΛΩΝ ΛΑΒΕ / Molon Lab",
    "&quot;Silent Majority&quot;",
    "&quot;Liberalism is a mental disorder&quot;",
    "Anything about 911",
    "American flag/eagle/Trump background image",
    "&quot;Libtard&quot;",
    "&quot;I support the current thing&quot; meme",
    "&quot;Childless libs&quot;",
    "&quot;cat lady&quot;",
    "&quot;Reeeeeeee&quot;",
    "Pepe the Frog",
    "&quot;Triggered&quot; meme",
    "Attacks on physical appearance (hair, weight, etc)",
    "&quot;Ok, groomer&quot;",
    "RT Ben Shapiro",
    "RT Charlie Kirk",
    "RT Donald Trump (oh wait lol)",
    "RT Candace Owens",
    "RT Tucker Carlson",
    "RT Elon Musk",
    "RT Jack Posobiec",

]